#! /bin/bash

set -euo pipefail

cd "$(dirname "$0")"
cd ..

./misc/style/run-all-style-checks.py

# Build Fast Downward with all CPUs.
CPUS=$(python -c "import multiprocessing as m; print(m.cpu_count())")
set -x
./build.py -j${CPUS}
./build.py --debug -j${CPUS}

./misc/tests/run-all-code-tests
