#! /bin/bash
#
# Test that the translator works for all supported python versions.
#
# Run small test on a few problems.
# $ ./test-translator
#
# Run bigger test on the first problem of each domain.
# $ ./test-translator first
#
# Run test on specific problems.
# $ ./test-translator gripper:prob01.pddl depot:pfile1
#
# Returns 0 on success and 1 if an error occurs.

set -e

for PYTHON in python2.6 python2.7 python3; do
    # Returns 0 if command is found.
    command -v $PYTHON >/dev/null 2>&1
    # Only test those python versions that are installed.
    if [ $? -eq 0 ]; then
        echo
        $PYTHON -V
        $PYTHON test-translator.py "$@"
    fi
done

rm -f output.sas

echo "TESTS PASSED"



