#! /bin/bash

## Run this to update the buildmaster with the newest config file from
## the repository. This automatically downloads the newest version of
## the master.cfg and informs the buildbot of the config change.

set -e
X="sudo -u buildbot"
cd /var/lib/buildbot/downward
$X mv master.cfg master.cfg.bak
$X wget http://hg.fast-downward.org/raw-file/tip/misc/master.cfg
$X chmod go-r master.cfg
$X buildbot checkconfig
sudo /etc/init.d/buildbot reload
$X rm -f master.cfg.bak
