#! /bin/bash
#
# Test that the translator works for all supported python versions.
#
# Run small test on a few problems.
# $ ./test-translator
#
# Run bigger test on the first problem of each domain.
# $ ./test-translator first
#
# Run even bigger test on the whole benchmark suite.
# $ ./test-translator all
#
# Run test on specific problems.
# $ ./test-translator gripper:prob01.pddl depot:pfile1
#
# Returns 0 on success and 1 if an error occurs.

set -ue

# Create clean tmp dir.
SAS_FILES=/tmp/$(whoami)/sas-files/
rm -rf "$SAS_FILES"
mkdir -p "$SAS_FILES"

cd "$(dirname "$0")"

export PYTHONHASHSEED=random

for PYTHON in python2.7 python3; do
    echo
    $PYTHON -V
    $PYTHON test-translator.py "$@"
done


# Check that all python versions produced the same output.sas

cd "$SAS_FILES"

printf "\n*********************************************************\n\n"
for TASK in $(ls)
do
    echo "Comparing SAS+ files for $TASK:"
    cd $TASK
    # Loop over all pairs
    set -- $(ls)
    for a; do
        shift
        for b; do
            printf "%s vs. %s\n" "$a" "$b"
            diff $a $b || exit 1
        done
    done
    cd ..
    echo
done

# Remove tmp dir.
rm -rf "$SAS_FILES"

echo "TESTS PASSED"
