#! /bin/bash

set -exuo pipefail

# Change into the root directory of the repository.
cd "$(dirname "$0")/../../"

./build.py
./build.py --debug

pytest driver/tests.py

cd misc/

./autodoc/autodoc.py --dry-run > /dev/null

cd tests/

./test-exitcodes.py
./test-standard-configs.py
./test-memory-leaks.py
./test-translator.py benchmarks/ all

echo
echo "All code tests passed"
