site_name: Fast Downward Documentation
nav:
  - Getting started: documentation/quick-start.md
  - PDDL Support: documentation/PddlSupport.md
  - Option Syntax: documentation/option-syntax.md
  - Search Component: documentation/search/
  - Exit Codes: documentation/exit-codes.md
repo_url: https://github.com/aibasel/downward/
edit_uri: edit/main/docs/ # TODO update to correct directory
site_url: https://ai.dmi.unibas.ch/_downward-test # TODO update
theme:
  name: material
  palette:
    primary: deep-orange
extra:
  version:
    provider: mike
plugins:
  - mike:
      version_selector: true
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
markdown_extensions:
#  - toc:
#      permalink: true

