site_name: Fast Downward Documentation
nav:
  - Getting started: documentation/quick-start.md
  - Planner usage: documentation/planner-usage.md
  - PDDL Support: documentation/pddl-support.md
  - Option Syntax: documentation/option-syntax.md
  - Search Component: documentation/search/
  - Exit Codes: documentation/exit-codes.md
repo_url: https://github.com/aibasel/downward/
edit_uri: edit/main/docs/ # TODO update to correct directory
site_url: https://ai.dmi.unibas.ch/_downward-test/documentation # TODO update
theme:
  name: material
  logo: img/driller.svg
  palette:
    primary: deep-orange
extra:
  version:
    provider: mike
plugins:
  - mike:
      version_selector: true
      deploy_prefix: 'documentation'
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#  - toc:
#      permalink: true

