#! /bin/bash
BASEDIR="$(dirname "$0")"
TEMPFILE=downward.tmp.$$
cat > $TEMPFILE
STATE_SIZE=$(command time --output=elapsed.time --append --format='%S\n%U\n' "$BASEDIR/dispatch" $TEMPFILE)
echo Dispatcher selected state size $STATE_SIZE.
UNIT_COST=$(command time --output=elapsed.time --append --format='%S\n%U\n' "$BASEDIR/unitcost" $TEMPFILE)
echo This is a $UNIT_COST task.
PLANNER="$BASEDIR/downward-$STATE_SIZE"
if [[ "$1" == "ipc" ]]; then
    CONFIG="$2"
    shift 2
    if [[ "$CONFIG" == "seq-sat-fd-autotune" ]]; then
        # TODO: Erez: take care of this.
        "$PLANNER" "TODO: options" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-sat-fdss-1" ]]; then
        "$BASEDIR/downward-seq-sat-fdss-1.py" "$UNIT_COST" "$PLANNER" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-sat-fdss-2" ]]; then
        # TODO: Malte and Gabi: take care of this.
        "$PLANNER" "TODO: options" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-sat-lama-2008" ]]; then
        # TODO: Malte: take care of this.
        "$PLANNER" "TODO: options" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-sat-lama-2011" ]]; then
        # TODO: Malte: take care of this.
        "$PLANNER" "TODO: options" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-fd-autotune" ]]; then
        # TODO: Erez: take care of this.
        "$PLANNER" "TODO: options" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-fdss-1" ]]; then
        "$BASEDIR/downward-seq-opt-fdss-1.py" "$PLANNER" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-fdss-2" ]]; then
        # TODO: Malte and Gabi: take care of this.
        "$PLANNER" "TODO: options" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-selmax" ]]; then
        "$PLANNER" --search "astar(selmax(lmcut(),lmcount(lm_merged(lm_hm(m=1),lm_rhw()),admissible=true),training_set=1000),mpd=true)" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-bjolp" ]]; then
        "$PLANNER" --search "astar(lmcount(lm_merged(lm_rhw(),lm_hm(m=1)),admissible=true),mpd=true)" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-lmcut" ]]; then
        "$PLANNER" --search "astar(lmcut())" "$@" < $TEMPFILE
    elif [[ "$CONFIG" == "seq-opt-merge-and-shrink" ]]; then
        # TODO: Malte: take care of this.
        # The following configs were recommended by Raz and should be
        # run as a 50%/50% sequential portfolio, with the shrink_strategy=12
        # one first since it's more likely to run out of memory quickly.
        "$PLANNER" --search "astar(mas(max_states=1,merge_strategy=5,shrink_strategy=12))" "$@" < $TEMPFILE
        ## "$PLANNER" --search "astar(mas(max_states=200000,merge_strategy=5,shrink_strategy=7))" "$@" < $TEMPFILE
    else
        echo "unknown IPC planner name: $2"
        exit 2
    fi
else
    "$PLANNER" "$@" < $TEMPFILE
fi
rm -f $TEMPFILE
