#!/bin/sh
# $1 - preprocessor output file

gawk 'BEGIN {unit = 1;} {if (($1 == "end_metric") && (last == 0)) {exit(0);} if (($1 == "end_operator") && (last != 1)) {unit=0; exit(0);} last = $1;} END {print (unit == 1 ? "unit" : "nonunit");}' $1