#! /bin/bash

cd "$(dirname "$0")"
BASEDIR="$(pwd)"
tar xvzf Osi-0.103.0.tgz || exit 1
cd Osi-0.103.0 || exit 1
./configure --prefix "$BASEDIR/coin" --enable-static=yes --without-lapack || exit 1
make || exit 1
make test || exit 1 
make install || exit 1
cd ..
rm -r Osi-0.103.0
