#! /bin/bash

cd preprocess
make || exit 1
cd ..

cd search
make || exit 1
make release || exit 1
cd ..

type flex >& /dev/null
if [ $? != 0 ]; then
    echo cannot build validator: flex not found
    exit 1
fi

type bison >& /dev/null
if [ $? != 0 ]; then
    echo cannot build validator: bison not found
    exit 1
fi

cd VAL
make validate || exit 1
cp validate ..
cd ..
