#! /bin/bash

function run-domain {
    DOMAIN="$1"
    shift
    rm -f $DOMAIN.log
    for PATTERN in "$@"; do
        for TASK in ../../benchmarks/$DOMAIN/$PATTERN; do
            echo -n "$TASK... "
            RESULT=$(./additive-hmax.py $TASK | grep -o '^[0-9][0-9]*$')
            echo $RESULT
            echo "$TASK... $RESULT" >> $DOMAIN.log
        done
    done
}

# run-domain blocks prob*.pddl
# run-domain gripper prob*.pddl
# run-domain logistics00 prob*.pddl
# run-domain logistics98 prob{01,05,17,31,32,33,35}.pddl
# run-domain miconic s*-0.pddl
# run-domain satellite p[01]?-pfile*.pddl
# run-domain satellite p2?-*.pddl
# run-domain logistics98 prob{0?,1?,34,20}.pddl
# run-domain logistics98 prob{21,22,23,24,26,27,29}.pddl
# run-domain logistics98 prob{25,30,28}.pddl
# run-domain tpp p??.pddl
# run-domain driverlog pfile? pfile??
# run-domain zenotravel pfile? pfile??
# run-domain pipesworld-tankage p21-*.pddl
# run-domain pipesworld-notankage p{20,21,22,23,24,25,26,27}-*.pddl
# run-domain depot pfile? pfile??
run-domain airport p??-airport*.pddl
