#! /bin/bash
rm -f downward.tmp.*
rm -f output.sas
rm -f output
rm -f elapsed.time
rm -f plan_numbers_and_cost
rm -f sas_plan

NUM=1
while [[ -e sas_plan.$NUM ]]; do
    rm -f sas_plan.$NUM
    NUM=$((NUM + 1))
done
