#! /usr/bin/env python
# -*- coding: utf-8 -*-

import sys

from driver.main import main


if __name__ == "__main__":
    exitcode = main()
    print "*** Exit with %d" % exitcode
    sys.exit(exitcode)
