#! /bin/bash

set -e

cd "$(dirname "$0")"
BASEDIR="$(pwd)"
tar xvzf Osi-0.103.0.tgz
cd Osi-0.103.0
./configure --prefix "$BASEDIR/coin" --enable-static=yes --enable-shared=no --without-lapack
make
make test
make install
cd ..
rm -r Osi-0.103.0
