env:
  GUROBI_URL: ${{ secrets.GUROBI1302_MACOS_URL }}
  GUROBI_LICENSE_URL: ${{ secrets.GUROBI_LICENSE_URL }}

  GUROBI_HOME: /Users/runner/lib/gurobi1302/macos_universal2
  GUROBI_LIB: /Users/runner/lib/gurobi1302/macos_universal2/lib
  DYLD_LIBRARY_PATH: /Users/runner/lib/gurobi1302/macos_universal2/lib

  GRB_LICENSE_FILE: /Users/runner/gurobi.lic

steps:
  - name: Clone repository
    uses: actions/checkout@v3

  - name: Install Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.version.python }}

  - name: Install Gurobi
    if: env.GUROBI_URL != ''
    run: |
      curl \
        --fail \
        --location \
        --silent \
        --show-error \
        "$GUROBI_URL" \
        --output "$RUNNER_TEMP/gurobi.pkg"

      sudo installer \
        -pkg "$RUNNER_TEMP/gurobi.pkg" \
        -target /

      mkdir -p "$HOME/lib/gurobi1302"

      cp -R \
        /Library/gurobi1302/macos_universal2 \
        "$HOME/lib/gurobi1302/"

      rm "$RUNNER_TEMP/gurobi.pkg"

      test -f "$GUROBI_HOME/include/gurobi_c.h"
      test -d "$GUROBI_HOME/lib"

  - name: Compile planner
    run: |
      export CXXFLAGS="-Werror"
      ./build.py --debug
      ./build.py
