---
name: macOS

on:
  push:
    branches: [main, release-*, issue1199-part2-algs-rebased]
  pull_request:
    branches: [main, release-*]

jobs:
  compile:
    name: Compile planner
    timeout-minutes: 60
    runs-on: macos-14

    env:
      GUROBI_URL: ${{ secrets.GUROBI1302_OSX_URL }}
      GUROBI_HOME: /Users/runner/lib/gurobi1302/macos_universal2
      DYLD_LIBRARY_PATH: /Users/runner/lib/gurobi1302/macos_universal2/lib

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Gurobi
        if: env.GUROBI_URL != ''
        run: |
          curl \
            --fail \
            --location \
            --silent \
            --show-error \
            "$GUROBI_URL" \
            --output "$RUNNER_TEMP/gurobi.pkg"

          sudo installer \
            -pkg "$RUNNER_TEMP/gurobi.pkg" \
            -target /

          mkdir -p "$HOME/lib/gurobi1302"

          cp -R \
            /Library/gurobi1302/macos_universal2 \
            "$HOME/lib/gurobi1302/"

          rm "$RUNNER_TEMP/gurobi.pkg"

          test -f "$GUROBI_HOME/include/gurobi_c.h"
          test -d "$GUROBI_HOME/lib"

      - name: Compile planner
        run: |
          export CXXFLAGS="-Werror"
          ./build.py --debug
          ./build.py
