---
name: Code style tests

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:
  style:
    name: Test code style
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install tox
          sudo apt-get -y install clang-tidy-16

      - name: Install uncrustify
        run: |
          # Set up uncrustify.
          wget https://github.com/uncrustify/uncrustify/archive/uncrustify-0.72.0.tar.gz
          tar xzf uncrustify-0.72.0.tar.gz
          cd uncrustify-uncrustify-0.72.0
          mkdir build
          cd build
          cmake ../
          make -j2
          mv uncrustify ../../
          cd ../../
          rm -rf uncrustify-0.72.0.tar.gz uncrustify-uncrustify-0.72.0

      - name: Run code style tests
        run: |
          export PATH="$(pwd):$PATH" # Add uncrustify to path.
          cd misc/
          tox -e style,clang-tidy

...
