---
name: Update website

on:
  push:
    branches:
      - issue1174

jobs:
  generate-documentation:
    name: Generate documentation
    if: github.repository == 'roeger/downward'
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          path: downward

      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: roeger/downward-website
          token: ${{ secrets.DOWNWARD_WEBSITE_PAT }}
          path: downward-website
          ref: tip

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run autodoc
        run: |
          # generate documentation for search component
          cd downward
          python3 build.py
          cd misc/autodoc
          python3 -m pip install -r requirements.txt
          python3 generate-docs.py
          cd ../../..

      - name: Move website material to website repo
        run: |
          cd downward-website
          ls *
          git rm -r * # wipe content and fill it from scratch
          cp ../downward/misc/autodoc/mkdocs.yml .
          mkdir -p docs/
          cp ../downward/docs/*.md docs/
          mkdir docs/search
          cp ../downward/misc/autodoc/docs/* docs/search
          git add docs
          git add mkdocs.yml
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          git commit -m "update documentation"
          git push

          

